site_name: Sudokumentation
site_author: Valentin Wyss
docs_dir: content
repo_url: https://github.com/wyssard/sudoku2

nav:
  - Home:
    - Overview: index.md
    - Solving Process: solving_process.md
  - Usage: 
    - Standard Solver: standard_solvers.md
    - Custom Solver: custom_solver.md
    - API Guide: api_guide.md
  - API: api/
    

theme: 
  name: material
  language: en
  font:
    text: Lora

  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - primary: white

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
            options:
              show_source: false
  - gen-files:
      scripts:
        - gen_api_docs.py
  - literate-nav:
      nav_file: modules.md
  - glightbox


markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"