site_name: Sudokumentation
site_author: Valentin Wyss
docs_dir: content
repo_url: https://github.com/wyssard/sudoku2

nav:
  - Home: index.md
  - API Guide: api_guide.md
  - Standard Solver: standard_solvers.md
  - Solving Process: solving_process.md
  - Custom Solver: custom_solver.md
  - API: api/modules.md

theme: 
  name: material
  language: en

markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format